name: Deploy Firebase Functions

on:
    push:
        branches:
            - maaster

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '18'

            - name: Install Firebase Tools
              run: npm install -g firebase-tools

            - name: Navigate to Backend Directory
              run: cd backend

            - name: Install Dependencies
              run: npm install

            - name: Login to Firebase
              run: firebase login:ci --token "${{ secrets.FIREBASE_TOKEN }}"

            - name: Deploy Firebase Functions
              run: firebase deploy --only functions
# name: Deploy to Firebase

# on:
#     push:
#         branches:
#             - master

# jobs:
#     build-and-deploy:
#         runs-on: ubuntu-latest

#         steps:
#             - uses: actions/checkout@v3
#             - uses: actions/setup-node@v3
#               with:
#                   node-version: 18

#             - name: Install Dependencies
#               run: npm install --prefix ./backend

#             - uses: FirebaseExtended/action-hosting-deploy@v0
#               with:
#                   repoToken: '${{ secrets.GIT_TOKEN }}'
#                   firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }} # Make sure this line is included
#                   projectId: case-module
#                   expires: 7d
#                   entryPoint: backend
#                   firebaseToolsVersion: latest
#                   channelId: live
