name: Firebase Deploy

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '18'

            - name: Install Firebase Tools
              run: npm install -g firebase-tools

            - name: Navigate to Backend Directory
              run: cd backend

            - name: Install Dependencies
              run: npm install

            - name: Firebase Login
              run: npx firebase login --no-localhost

            - name: Firebase Deploy
              run: npx firebase deploy --only functions
              env:
                  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
